### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by prasantadh** [prasantadh/fyp-demo#2]
# Business Rules
- [ ] Decide who the actors are
    - [ ] the properties of the actors
    - [x] the limitation on each of those actors (are they unique, optional, both? do they qualify as primary key) 
    - [ ] The relationship of this actor to any other actors 
 
# ERD 

#
